require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/snacks", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Snack. As you add validations to Snack, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      name: "Chocolate Bar",
      description: "Sweet and crunchy",
      img_url: "https://example.com/choco.jpg"
    }
  end

  let(:invalid_attributes) do
    {
      name: nil, # invalid because name is required
      description: "Missing name",
      img_url: "https://example.com/invalid.jpg"
    }
  end

  let(:user) { create(:user) }

  before do
    allow_any_instance_of(ApplicationController)
      .to receive(:require_authentication)
            .and_return(true)

    allow(Current).to receive(:user).and_return(user)
    allow(Current).to receive(:session).and_return(build(:session, user: user))
  end

  describe "GET /index" do
    it "renders a successful response" do
      Snack.create! valid_attributes
      get snacks_url
      expect(response).to be_successful
    end
  end

  # describe "GET /show" do
  #   it "renders a successful response" do
  #     snack = Snack.create! valid_attributes
  #     get snack_url(snack)
  #     expect(response).to be_successful
  #   end
  # end

  describe "GET /new" do
    it "renders a successful response" do
      get new_snack_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      snack = user.snacks.create!(valid_attributes)
      get edit_snack_url(snack)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Snack" do
        expect {
          post snacks_url, params: { snack: valid_attributes }
        }.to change(Snack, :count).by(1)
      end

      it "redirects to the created snack" do
        post snacks_url, params: { snack: valid_attributes }
        expect(response).to redirect_to(snacks_url)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Snack" do
        expect {
          post snacks_url, params: { snack: invalid_attributes }
        }.not_to change(Snack, :count)
      end

      it "renders a response with 422 status (to display 'new' template)" do
        post snacks_url, params: { snack: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    let(:new_attributes) do
      {
        name: "Updated Choco Bites",
        description: "Now with extra crunch!"
      }
    end

    context "with valid parameters" do
      it "updates the requested snack" do
        snack = user.snacks.create!(valid_attributes)
        patch snack_url(snack), params: { snack: new_attributes }
        snack.reload
        expect(snack.name).to eq("Updated Choco Bites")
        expect(snack.description).to eq("Now with extra crunch!")
      end

      it "redirects to the snack" do
        snack = user.snacks.create!(valid_attributes)
        patch snack_url(snack), params: { snack: new_attributes }
        expect(response).to redirect_to(snacks_url)
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (to display 'edit' template)" do
        snack = user.snacks.create!(valid_attributes)
        patch snack_url(snack), params: { snack: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested snack" do
      snack = user.snacks.create!(valid_attributes)

      expect {
        delete snack_url(snack)
      }.to change(Snack, :count).by(-1)
    end

    it "redirects to the snacks list" do
      snack = user.snacks.create!(valid_attributes)
      delete snack_url(snack)
      expect(response).to redirect_to(snacks_url)
    end
  end
end
